[workspace]
members = ["syntax", "core", "viper-backend"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
color-eyre = "0.6.2"
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.38"
tracing = "0.1.37"
mist-syntax = { path = "./syntax" }
mist-core = { path = "./core" }
salsa = { git = "https://github.com/salsa-rs/salsa.git", package = "salsa-2022" }
# silvers = { git = "https://github.com/oeb25/vipers.git" }
silvers = { path = "../vipers/silvers" }

[profile.release]
debug = true
