import * as monaco from "monaco-editor";

// Theme is "vitesse-dark.json" taken from https://github.com/antfu/vscode-theme-vitesse/blob/main/themes/vitesse-dark.json
// Convert themes at https://vsctim.vercel.app/
export const VITESSE_DARK = "Vitesse-Dark";
const theme: monaco.editor.IStandaloneThemeData = {
  inherit: true,
  base: "vs-dark",
  colors: {
    focusBorder: "#00000000",
    foreground: "#dbd7caee",
    descriptionForeground: "#dedcd590",
    errorForeground: "#cb7676",
    "textLink.foreground": "#4d9375",
    "textLink.activeForeground": "#4d9375",
    "textBlockQuote.background": "#121212",
    "textBlockQuote.border": "#191919",
    "textCodeBlock.background": "#121212",
    "textPreformat.foreground": "#d1d5da",
    "textSeparator.foreground": "#586069",
    "button.background": "#4d9375",
    "button.foreground": "#121212",
    "button.hoverBackground": "#4d9375",
    "checkbox.background": "#181818",
    "checkbox.border": "#2f363d",
    "dropdown.background": "#121212",
    "dropdown.border": "#191919",
    "dropdown.foreground": "#dbd7caee",
    "dropdown.listBackground": "#181818",
    "input.background": "#181818",
    "input.border": "#191919",
    "input.foreground": "#dbd7caee",
    "input.placeholderForeground": "#dedcd590",
    "inputOption.activeBackground": "#dedcd530",
    "badge.foreground": "#121212",
    "badge.background": "#dedcd590",
    "progressBar.background": "#4d9375",
    "titleBar.activeForeground": "#bfbaaa",
    "titleBar.activeBackground": "#121212",
    "titleBar.inactiveForeground": "#959da5",
    "titleBar.inactiveBackground": "#121212",
    "titleBar.border": "#181818",
    "activityBar.foreground": "#dbd7caee",
    "activityBar.inactiveForeground": "#dedcd530",
    "activityBar.background": "#121212",
    "activityBarBadge.foreground": "#121212",
    "activityBarBadge.background": "#bfbaaa",
    "activityBar.activeBorder": "#4d9375",
    "activityBar.border": "#191919",
    "sideBar.foreground": "#bfbaaa",
    "sideBar.background": "#121212",
    "sideBar.border": "#191919",
    "sideBarTitle.foreground": "#dbd7caee",
    "sideBarSectionHeader.foreground": "#dbd7caee",
    "sideBarSectionHeader.background": "#121212",
    "sideBarSectionHeader.border": "#191919",
    "list.hoverForeground": "#dbd7caee",
    "list.inactiveSelectionForeground": "#dbd7caee",
    "list.activeSelectionForeground": "#dbd7caee",
    "list.hoverBackground": "#181818",
    "list.inactiveSelectionBackground": "#181818",
    "list.activeSelectionBackground": "#181818",
    "list.inactiveFocusBackground": "#121212",
    "list.focusBackground": "#181818",
    "tree.indentGuidesStroke": "#2f363d",
    "notificationCenterHeader.foreground": "#959da5",
    "notificationCenterHeader.background": "#121212",
    "notifications.foreground": "#dbd7caee",
    "notifications.background": "#121212",
    "notifications.border": "#191919",
    "notificationsErrorIcon.foreground": "#cb7676",
    "notificationsWarningIcon.foreground": "#d4976c",
    "notificationsInfoIcon.foreground": "#6394bf",
    "pickerGroup.border": "#444d56",
    "pickerGroup.foreground": "#dbd7caee",
    "quickInput.background": "#121212",
    "quickInput.foreground": "#dbd7caee",
    "statusBar.foreground": "#bfbaaa",
    "statusBar.background": "#121212",
    "statusBar.border": "#191919",
    "statusBar.noFolderBackground": "#121212",
    "statusBar.debuggingBackground": "#181818",
    "statusBar.debuggingForeground": "#bfbaaa",
    "statusBarItem.prominentBackground": "#181818",
    "editorGroupHeader.tabsBackground": "#121212",
    "editorGroupHeader.tabsBorder": "#191919",
    "editorGroup.border": "#191919",
    "tab.activeForeground": "#dbd7caee",
    "tab.inactiveForeground": "#959da5",
    "tab.inactiveBackground": "#121212",
    "tab.activeBackground": "#121212",
    "tab.hoverBackground": "#181818",
    "tab.unfocusedHoverBackground": "#121212",
    "tab.border": "#191919",
    "tab.unfocusedActiveBorderTop": "#191919",
    "tab.activeBorder": "#191919",
    "tab.unfocusedActiveBorder": "#191919",
    "tab.activeBorderTop": "#dedcd590",
    "breadcrumb.foreground": "#959da5",
    "breadcrumb.focusForeground": "#dbd7caee",
    "breadcrumb.background": "#181818",
    "breadcrumb.activeSelectionForeground": "#eeeeee15",
    "breadcrumbPicker.background": "#121212",
    "editor.foreground": "#dbd7caee",
    "editor.background": "#121212",
    "editorWidget.background": "#121212",
    "editor.foldBackground": "#eeeeee10",
    "editor.lineHighlightBackground": "#181818",
    "editorLineNumber.foreground": "#dedcd530",
    "editorLineNumber.activeForeground": "#bfbaaa",
    "editorIndentGuide.background": "#ffffff15",
    "editorIndentGuide.activeBackground": "#ffffff30",
    "editorWhitespace.foreground": "#ffffff15",
    "editor.findMatchBackground": "#e6cc7722",
    "editor.findMatchHighlightBackground": "#e6cc7744",
    "editor.inactiveSelectionBackground": "#eeeeee08",
    "editor.selectionBackground": "#eeeeee15",
    "editor.selectionHighlightBackground": "#eeeeee08",
    "editor.wordHighlightBackground": "#1c6b4805",
    "editor.wordHighlightStrongBackground": "#1c6b4810",
    "editorBracketMatch.background": "#4d937520",
    "diffEditor.insertedTextBackground": "#4d937522",
    "diffEditor.removedTextBackground": "#ab595922",
    "scrollbar.shadow": "#0000",
    "scrollbarSlider.background": "#dedcd510",
    "scrollbarSlider.hoverBackground": "#dedcd530",
    "scrollbarSlider.activeBackground": "#dedcd530",
    "editorOverviewRuler.border": "#111",
    "panel.background": "#121212",
    "panel.border": "#191919",
    "panelTitle.activeBorder": "#4d9375",
    "panelTitle.activeForeground": "#dbd7caee",
    "panelTitle.inactiveForeground": "#959da5",
    "panelInput.border": "#2f363d",
    "terminal.foreground": "#dbd7caee",
    "terminal.selectionBackground": "#eeeeee15",
    "terminal.ansiBrightBlack": "#777777",
    "terminal.ansiBrightBlue": "#6394bf",
    "terminal.ansiBrightCyan": "#5eaab5",
    "terminal.ansiBrightGreen": "#4d9375",
    "terminal.ansiBrightMagenta": "#d9739f",
    "terminal.ansiBrightRed": "#cb7676",
    "terminal.ansiBrightWhite": "#ffffff",
    "terminal.ansiBrightYellow": "#e6cc77",
    "terminal.ansiBlack": "#393a34",
    "terminal.ansiBlue": "#6394bf",
    "terminal.ansiCyan": "#5eaab5",
    "terminal.ansiGreen": "#4d9375",
    "terminal.ansiMagenta": "#d9739f",
    "terminal.ansiRed": "#cb7676",
    "terminal.ansiWhite": "#dbd7caee",
    "terminal.ansiYellow": "#e6cc77",
    "gitDecoration.addedResourceForeground": "#4d9375",
    "gitDecoration.modifiedResourceForeground": "#6394bf",
    "gitDecoration.deletedResourceForeground": "#cb7676",
    "gitDecoration.untrackedResourceForeground": "#5eaab5",
    "gitDecoration.ignoredResourceForeground": "#dedcd530",
    "gitDecoration.conflictingResourceForeground": "#d4976c",
    "gitDecoration.submoduleResourceForeground": "#dedcd590",
    "editorGutter.modifiedBackground": "#6394bf",
    "editorGutter.addedBackground": "#4d9375",
    "editorGutter.deletedBackground": "#cb7676",
    "editorBracketHighlight.foreground1": "#5eaab5",
    "editorBracketHighlight.foreground2": "#4d9375",
    "editorBracketHighlight.foreground3": "#d4976c",
    "editorBracketHighlight.foreground4": "#d9739f",
    "editorBracketHighlight.foreground5": "#e6cc77",
    "editorBracketHighlight.foreground6": "#6394bf",
    "debugToolBar.background": "#121212",
    "editor.stackFrameHighlightBackground": "#a707",
    "editor.focusedStackFrameHighlightBackground": "#b808",
    "peekViewEditor.matchHighlightBackground": "#ffd33d33",
    "peekViewResult.matchHighlightBackground": "#ffd33d33",
    "peekViewEditor.background": "#121212",
    "peekViewResult.background": "#121212",
    "settings.headerForeground": "#dbd7caee",
    "settings.modifiedItemIndicator": "#4d9375",
    "welcomePage.buttonBackground": "#2f363d",
    "welcomePage.buttonHoverBackground": "#444d56",
    "problemsErrorIcon.foreground": "#cb7676",
    "problemsWarningIcon.foreground": "#d4976c",
    "problemsInfoIcon.foreground": "#6394bf",
    "editorError.foreground": "#cb7676",
    "editorWarning.foreground": "#d4976c",
    "editorInfo.foreground": "#6394bf",
    "editorHint.foreground": "#4d9375",
    "editorGutter.commentRangeForeground": "#dedcd530",
    "editorGutter.foldingControlForeground": "#dedcd590",
    "editorInlayHint.foreground": "#666666",
    "editorInlayHint.background": "#00000000",
    "editorStickyScroll.background": "#181818",
    "editorStickyScrollHover.background": "#181818",
  },
  rules: [
    {
      foreground: "#758575dd",
      token: "comment",
    },
    {
      foreground: "#758575dd",
      token: "punctuation.definition.comment",
    },
    {
      foreground: "#758575dd",
      token: "string.comment",
    },
    {
      foreground: "#666666",
      token: "delimiter.bracket",
    },
    {
      foreground: "#666666",
      token: "delimiter",
    },
    {
      foreground: "#666666",
      token: "invalid.illegal.character-not-allowed-here.html",
    },
    {
      foreground: "#666666",
      token: "keyword.operator.rest",
    },
    {
      foreground: "#666666",
      token: "keyword.operator.spread",
    },
    {
      foreground: "#666666",
      token: "keyword.operator.type.annotation",
    },
    {
      foreground: "#666666",
      token: "keyword.operator.relational.ts",
    },
    {
      foreground: "#666666",
      token: "meta.brace",
    },
    {
      foreground: "#666666",
      token: "meta.tag.block.any.html",
    },
    {
      foreground: "#666666",
      token: "meta.tag.inline.any.html",
    },
    {
      foreground: "#666666",
      token: "meta.tag.structure.input.void.html",
    },
    {
      foreground: "#666666",
      token: "meta.type.annotation",
    },
    {
      foreground: "#666666",
      token: "storage.type.function.arrow",
    },
    {
      foreground: "#666666",
      token: "keyword.operator.type",
    },
    {
      foreground: "#666666",
      token: "meta.objectliteral.ts",
    },
    {
      foreground: "#666666",
      token: "punctuation",
    },
    {
      foreground: "#c99076",
      token: "constant",
    },
    {
      foreground: "#c99076",
      token: "entity.name.constant",
    },
    {
      foreground: "#c99076",
      token: "variable.language",
    },
    {
      foreground: "#c99076",
      token: "meta.definition.variable",
    },
    {
      foreground: "#80a665",
      token: "entity",
    },
    {
      foreground: "#80a665",
      token: "entity.name",
    },
    {
      foreground: "#dbd7caee",
      token: "variable.parameter.function",
    },
    {
      foreground: "#4d9375",
      token: "entity.name.tag",
    },
    {
      foreground: "#4d9375",
      token: "tag.html",
    },
    {
      foreground: "#80a665",
      token: "entity.name.function",
    },
    {
      foreground: "#4d9375",
      token: "keyword",
    },
    {
      foreground: "#4d9375",
      token: "storage.type.class.jsdoc",
    },
    {
      foreground: "#cb7676",
      token: "storage",
    },
    {
      foreground: "#cb7676",
      token: "storage.type",
    },
    {
      foreground: "#cb7676",
      token: "support.type.builtin",
    },
    {
      foreground: "#cb7676",
      token: "constant.language.undefined",
    },
    {
      foreground: "#cb7676",
      token: "constant.language.null",
    },
    {
      foreground: "#dbd7caee",
      token: "storage.modifier.package",
    },
    {
      foreground: "#dbd7caee",
      token: "storage.modifier.import",
    },
    {
      foreground: "#dbd7caee",
      token: "storage.type.java",
    },
    {
      foreground: "#c98a7d",
      token: "string",
    },
    {
      foreground: "#c98a7d",
      token: "string punctuation.section.embedded source",
    },
    {
      foreground: "#c98a7d",
      token: "attribute.value",
    },
    {
      foreground: "#c98a7d99",
      token: "punctuation.definition.string",
    },
    {
      foreground: "#c98a7d99",
      token: "punctuation.support.type.property-name",
    },
    {
      foreground: "#b8a965",
      token: "support",
    },
    {
      foreground: "#b8a965",
      token: "property",
    },
    {
      foreground: "#b8a965",
      token: "meta.property-name",
    },
    {
      foreground: "#b8a965",
      token: "meta.object-literal.key",
    },
    {
      foreground: "#b8a965",
      token: "entity.name.tag.yaml",
    },
    {
      foreground: "#b8a965",
      token: "attribute.name",
    },
    {
      foreground: "#bd976a",
      token: "entity.other.attribute-name",
    },
    {
      foreground: "#bd976a",
      token: "invalid.deprecated.entity.other.attribute-name.html",
    },
    {
      foreground: "#bd976a",
      token: "variable",
    },
    {
      foreground: "#bd976a",
      token: "identifier",
    },
    {
      foreground: "#5da9a7",
      token: "support.type.primitive",
    },
    {
      foreground: "#5da9a7",
      token: "entity.name.type",
    },
    {
      foreground: "#db889a",
      token: "namespace",
    },
    {
      foreground: "#cb7676",
      token: "keyword.operator",
    },
    {
      foreground: "#cb7676",
      token: "meta.var.expr.ts",
    },
    {
      fontStyle: "italic",
      foreground: "#fdaeb7",
      token: "invalid.broken",
    },
    {
      fontStyle: "italic",
      foreground: "#fdaeb7",
      token: "invalid.deprecated",
    },
    {
      fontStyle: "italic",
      foreground: "#fdaeb7",
      token: "invalid.illegal",
    },
    {
      fontStyle: "italic",
      foreground: "#fdaeb7",
      token: "invalid.unimplemented",
    },
    {
      fontStyle: "italic underline",
      background: "#f97583",
      foreground: "#24292e",
      token: "carriage-return",
    },
    {
      foreground: "#fdaeb7",
      token: "message.error",
    },
    {
      foreground: "#c98a7d",
      token: "string variable",
    },
    {
      foreground: "#c4704f",
      token: "source.regexp",
    },
    {
      foreground: "#c4704f",
      token: "string.regexp",
    },
    {
      foreground: "#c98a7d",
      token: "string.regexp.character-class",
    },
    {
      foreground: "#c98a7d",
      token: "string.regexp constant.character.escape",
    },
    {
      foreground: "#c98a7d",
      token: "string.regexp source.ruby.embedded",
    },
    {
      foreground: "#c98a7d",
      token: "string.regexp string.regexp.arbitrary-repitition",
    },
    {
      foreground: "#e6cc77",
      token: "string.regexp constant.character.escape",
    },
    {
      foreground: "#c99076",
      token: "support.constant",
    },
    {
      foreground: "#4C9A91",
      token: "constant.numeric",
    },
    {
      foreground: "#4C9A91",
      token: "number",
    },
    {
      foreground: "#cb7676",
      token: "keyword.other.unit",
    },
    {
      foreground: "#4d9375",
      token: "constant.language.boolean",
    },
    {
      foreground: "#4d9375",
      token: "constant.language",
    },
    {
      foreground: "#4d9375",
      token: "meta.module-reference",
    },
    {
      foreground: "#d4976c",
      token: "punctuation.definition.list.begin.markdown",
    },
    {
      fontStyle: "bold",
      foreground: "#4d9375",
      token: "markup.heading",
    },
    {
      fontStyle: "bold",
      foreground: "#4d9375",
      token: "markup.heading entity.name",
    },
    {
      foreground: "#5DA994",
      token: "markup.quote",
    },
    {
      fontStyle: "italic",
      foreground: "#dbd7caee",
      token: "markup.italic",
    },
    {
      fontStyle: "bold",
      foreground: "#dbd7caee",
      token: "markup.bold",
    },
    {
      foreground: "#4d9375",
      token: "markup.raw",
    },
    {
      background: "#86181d",
      foreground: "#fdaeb7",
      token: "markup.deleted",
    },
    {
      background: "#86181d",
      foreground: "#fdaeb7",
      token: "meta.diff.header.from-file",
    },
    {
      background: "#86181d",
      foreground: "#fdaeb7",
      token: "punctuation.definition.deleted",
    },
    {
      background: "#144620",
      foreground: "#85e89d",
      token: "markup.inserted",
    },
    {
      background: "#144620",
      foreground: "#85e89d",
      token: "meta.diff.header.to-file",
    },
    {
      background: "#144620",
      foreground: "#85e89d",
      token: "punctuation.definition.inserted",
    },
    {
      background: "#c24e00",
      foreground: "#ffab70",
      token: "markup.changed",
    },
    {
      background: "#c24e00",
      foreground: "#ffab70",
      token: "punctuation.definition.changed",
    },
    {
      foreground: "#2f363d",
      background: "#79b8ff",
      token: "markup.ignored",
    },
    {
      foreground: "#2f363d",
      background: "#79b8ff",
      token: "markup.untracked",
    },
    {
      foreground: "#b392f0",
      fontStyle: "bold",
      token: "meta.diff.range",
    },
    {
      foreground: "#79b8ff",
      token: "meta.diff.header",
    },
    {
      fontStyle: "bold",
      foreground: "#79b8ff",
      token: "meta.separator",
    },
    {
      foreground: "#79b8ff",
      token: "meta.output",
    },
    {
      foreground: "#d1d5da",
      token: "brackethighlighter.tag",
    },
    {
      foreground: "#d1d5da",
      token: "brackethighlighter.curly",
    },
    {
      foreground: "#d1d5da",
      token: "brackethighlighter.round",
    },
    {
      foreground: "#d1d5da",
      token: "brackethighlighter.square",
    },
    {
      foreground: "#d1d5da",
      token: "brackethighlighter.angle",
    },
    {
      foreground: "#d1d5da",
      token: "brackethighlighter.quote",
    },
    {
      foreground: "#fdaeb7",
      token: "brackethighlighter.unmatched",
    },
    {
      foreground: "#c98a7d",
      token: "constant.other.reference.link",
    },
    {
      foreground: "#c98a7d",
      token: "string.other.link",
    },
    {
      foreground: "#c98a7d",
      token: "punctuation.definition.string.begin.markdown",
    },
    {
      foreground: "#c98a7d",
      token: "punctuation.definition.string.end.markdown",
    },
    {
      foreground: "#dedcd590",
      fontStyle: "underline",
      token: "markup.underline.link.markdown",
    },
    {
      foreground: "#6893BF",
      token: "type.identifier",
    },
    {
      foreground: "#80a665",
      token: "entity.other.attribute-name.html.vue",
    },
    {
      fontStyle: "normal",
      token: "invalid.illegal.unrecognized-tag.html",
    },
  ],
  encodedTokensColors: [],
};
monaco.editor.defineTheme(VITESSE_DARK, theme);
