name: Deploy app to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: extractions/setup-just@v1
        with:
          just-version: 1.9

      # - name: Set stable toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable

      - name: Build app once
        run: |
          just build-app

      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
            path: app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
